import type {
  IntegrationCategory,
  IntegrationTool,
  ToolConnection,
  ToolConfig,
  ProjectToolConfig,
} from "@renderer/types/integration";

export const categories: IntegrationCategory[] = [
  {
    id: "project-management",
    name: "项目管理",
    description: "任务与需求的来源和归宿",
  },
  {
    id: "source-control",
    name: "源码管理",
    description: "代码的版本管理",
  },
  {
    id: "ci-cd",
    name: "CI/CD",
    description: "构建、测试与交付",
  },
  {
    id: "deployment",
    name: "部署",
    description: "应用部署目标",
  },
  {
    id: "communication",
    name: "通讯",
    description: "通知与协作",
  },
  {
    id: "observability",
    name: "可观测性",
    description: "监控、日志与告警",
  },
];

export const tools: IntegrationTool[] = [
  // Project Management
  {
    id: "yunxiao-projex",
    name: "云效项目",
    description: "Projex — 任务与需求管理",
    categoryId: "project-management",
    connectionType: "api-token",
    connectionFields: [
      {
        key: "accessKey",
        label: "Access Key",
        type: "text",
        placeholder: "请输入阿里云 Access Key",
        helperText: "在阿里云控制台 RAM 访问控制中获取",
        helpLink: "https://ram.console.aliyun.com/manage/ak",
        required: true,
      },
      {
        key: "accessSecret",
        label: "Access Secret",
        type: "password",
        placeholder: "请输入阿里云 Access Secret",
        helperText: "与 Access Key 配对使用",
        required: true,
      },
    ],
    parameterFields: [
      {
        key: "defaultOrganization",
        label: "默认组织",
        type: "text",
        placeholder: "请输入默认组织名称",
        required: false,
      },
    ],
    projectConfigFields: [
      {
        key: "projectKey",
        label: "项目 Key",
        type: "text",
        placeholder: "当前项目对应的云效项目 Key",
        required: true,
      },
    ],
    logoIcon: "i-lucide-folder-kanban",
    logoColor: "text-primary",
    comingSoon: false,
  },
  {
    id: "jira",
    name: "Jira",
    description: "问题与项目跟踪",
    categoryId: "project-management",
    connectionType: "oauth",
    connectionFields: [],
    parameterFields: [],
    projectConfigFields: [],
    logoIcon: "i-lucide-ticket",
    logoColor: "text-warning",
    comingSoon: true,
  },
  {
    id: "linear",
    name: "Linear",
    description: "简洁的问题跟踪",
    categoryId: "project-management",
    connectionType: "oauth",
    connectionFields: [],
    parameterFields: [],
    projectConfigFields: [],
    logoIcon: "i-lucide-list-checks",
    logoColor: "text-secondary",
    comingSoon: true,
  },
  // Source Control
  {
    id: "yunxiao-codeup",
    name: "云效 Codeup",
    description: "代码托管与合并请求管理",
    categoryId: "source-control",
    connectionType: "api-token",
    connectionFields: [
      {
        key: "accessKey",
        label: "Access Key",
        type: "text",
        placeholder: "请输入阿里云 Access Key",
        helperText: "在阿里云控制台 RAM 访问控制中获取",
        helpLink: "https://ram.console.aliyun.com/manage/ak",
        required: true,
      },
      {
        key: "accessSecret",
        label: "Access Secret",
        type: "password",
        placeholder: "请输入阿里云 Access Secret",
        required: true,
      },
    ],
    parameterFields: [
      {
        key: "defaultOrganization",
        label: "默认代码组织",
        type: "text",
        placeholder: "请输入默认代码组织",
        required: false,
      },
      {
        key: "branchNaming",
        label: "分支命名规则",
        type: "select",
        options: [
          { label: "feature/{name}", value: "feature/{name}" },
          { label: "feat/{name}", value: "feat/{name}" },
          { label: "自定义", value: "custom" },
        ],
        required: false,
      },
    ],
    projectConfigFields: [
      {
        key: "repository",
        label: "代码库",
        type: "text",
        placeholder: "当前项目对应的代码库名称",
        required: true,
      },
    ],
    logoIcon: "i-lucide-git-branch",
    logoColor: "text-primary",
    comingSoon: false,
  },
  {
    id: "github",
    name: "GitHub",
    description: "GitHub 仓库与 PR",
    categoryId: "source-control",
    connectionType: "oauth",
    connectionFields: [],
    parameterFields: [],
    projectConfigFields: [],
    logoIcon: "i-lucide-github",
    logoColor: "text-highlighted",
    comingSoon: true,
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "GitLab 仓库与 MR",
    categoryId: "source-control",
    connectionType: "oauth",
    connectionFields: [],
    parameterFields: [],
    projectConfigFields: [],
    logoIcon: "i-lucide-gitlab",
    logoColor: "text-error",
    comingSoon: true,
  },
  // CI/CD
  {
    id: "yunxiao-flow",
    name: "云效流水线",
    description: "Flow — 持续集成与交付",
    categoryId: "ci-cd",
    connectionType: "api-token",
    connectionFields: [
      {
        key: "accessKey",
        label: "Access Key",
        type: "text",
        placeholder: "请输入阿里云 Access Key",
        helperText: "在阿里云控制台 RAM 访问控制中获取",
        helpLink: "https://ram.console.aliyun.com/manage/ak",
        required: true,
      },
      {
        key: "accessSecret",
        label: "Access Secret",
        type: "password",
        placeholder: "请输入阿里云 Access Secret",
        required: true,
      },
    ],
    parameterFields: [
      {
        key: "pipelineTemplate",
        label: "默认流水线模板",
        type: "text",
        placeholder: "请输入默认流水线模板 ID",
        required: false,
      },
      {
        key: "triggerMode",
        label: "触发方式",
        type: "select",
        options: [
          { label: "代码提交触发", value: "commit" },
          { label: "定时触发", value: "schedule" },
          { label: "手动触发", value: "manual" },
        ],
        required: false,
      },
    ],
    projectConfigFields: [
      {
        key: "pipelineId",
        label: "关联流水线",
        type: "text",
        placeholder: "当前项目关联的流水线 ID",
        required: true,
      },
    ],
    logoIcon: "i-lucide-play-circle",
    logoColor: "text-primary",
    comingSoon: false,
  },
  {
    id: "github-actions",
    name: "GitHub Actions",
    description: "使用 GitHub 自动化 CI/CD",
    categoryId: "ci-cd",
    connectionType: "oauth",
    connectionFields: [],
    parameterFields: [],
    projectConfigFields: [],
    logoIcon: "i-lucide-workflow",
    logoColor: "text-highlighted",
    comingSoon: true,
  },
  {
    id: "gitlab-ci",
    name: "GitLab CI",
    description: "GitLab 内置 CI/CD",
    categoryId: "ci-cd",
    connectionType: "oauth",
    connectionFields: [],
    parameterFields: [],
    projectConfigFields: [],
    logoIcon: "i-lucide-repeat",
    logoColor: "text-error",
    comingSoon: true,
  },
  // Deployment
  {
    id: "aliyun",
    name: "阿里云",
    description: "ECS / SAE / 函数计算部署",
    categoryId: "deployment",
    connectionType: "api-token",
    connectionFields: [
      {
        key: "accessKey",
        label: "Access Key",
        type: "text",
        placeholder: "请输入阿里云 Access Key",
        helperText: "在阿里云控制台 RAM 访问控制中获取",
        helpLink: "https://ram.console.aliyun.com/manage/ak",
        required: true,
      },
      {
        key: "accessSecret",
        label: "Access Secret",
        type: "password",
        placeholder: "请输入阿里云 Access Secret",
        required: true,
      },
    ],
    parameterFields: [
      {
        key: "region",
        label: "目标地域",
        type: "select",
        options: [
          { label: "华东1（杭州）", value: "cn-hangzhou" },
          { label: "华东2（上海）", value: "cn-shanghai" },
          { label: "华北2（北京）", value: "cn-beijing" },
          { label: "华南1（深圳）", value: "cn-shenzhen" },
        ],
        required: false,
      },
      {
        key: "instanceType",
        label: "实例规格",
        type: "text",
        placeholder: "如 ecs.t5-lc1m1.small",
        required: false,
      },
      {
        key: "environment",
        label: "环境标识",
        type: "select",
        options: [
          { label: "开发环境", value: "dev" },
          { label: "预发环境", value: "staging" },
          { label: "生产环境", value: "prod" },
        ],
        required: false,
      },
    ],
    projectConfigFields: [
      {
        key: "serviceName",
        label: "服务名称",
        type: "text",
        placeholder: "当前项目对应的服务名称",
        required: true,
      },
    ],
    logoIcon: "i-lucide-cloud",
    logoColor: "text-primary",
    comingSoon: false,
  },
  {
    id: "vercel",
    name: "Vercel",
    description: "前端应用部署",
    categoryId: "deployment",
    connectionType: "oauth",
    connectionFields: [],
    parameterFields: [],
    projectConfigFields: [],
    logoIcon: "i-lucide-triangle",
    logoColor: "text-highlighted",
    comingSoon: true,
  },
  // Communication
  {
    id: "dingtalk",
    name: "钉钉",
    description: "通知群消息与审批提醒",
    categoryId: "communication",
    connectionType: "api-token",
    connectionFields: [
      {
        key: "webhookUrl",
        label: "Webhook URL",
        type: "url",
        placeholder: "https://oapi.dingtalk.com/robot/send?access_token=...",
        helperText: "在钉钉群机器人设置中获取 Webhook 地址",
        required: true,
      },
      {
        key: "secret",
        label: "Secret",
        type: "password",
        placeholder: "签名密钥（如启用加签）",
        helperText: "如果启用了加签安全设置，需要填写",
        required: false,
      },
    ],
    parameterFields: [
      {
        key: "notificationGroup",
        label: "通知群名称",
        type: "text",
        placeholder: "请输入通知群名称",
        required: false,
      },
      {
        key: "eventTriggers",
        label: "触发事件",
        type: "checkbox-group",
        options: [
          { label: "阶段完成", value: "stage-completed" },
          { label: "阶段失败", value: "stage-failed" },
          { label: "需要审批", value: "approval-required" },
          { label: "Pipeline 完成", value: "pipeline-completed" },
        ],
        required: false,
      },
    ],
    projectConfigFields: [
      {
        key: "projectWebhookUrl",
        label: "项目专属 Webhook",
        type: "url",
        placeholder: "覆盖全局 Webhook（可选）",
        required: false,
      },
    ],
    logoIcon: "i-lucide-message-circle",
    logoColor: "text-info",
    comingSoon: false,
  },
  {
    id: "slack",
    name: "Slack",
    description: "团队消息与通知",
    categoryId: "communication",
    connectionType: "oauth",
    connectionFields: [],
    parameterFields: [],
    projectConfigFields: [],
    logoIcon: "i-lucide-hash",
    logoColor: "text-secondary",
    comingSoon: true,
  },
  // Observability
  {
    id: "aliyun-sls",
    name: "阿里云日志服务",
    description: "SLS — 日志查询与告警分析",
    categoryId: "observability",
    connectionType: "api-token",
    connectionFields: [
      {
        key: "accessKey",
        label: "Access Key",
        type: "text",
        placeholder: "请输入阿里云 Access Key",
        helperText: "在阿里云控制台 RAM 访问控制中获取",
        helpLink: "https://ram.console.aliyun.com/manage/ak",
        required: true,
      },
      {
        key: "accessSecret",
        label: "Access Secret",
        type: "password",
        placeholder: "请输入阿里云 Access Secret",
        required: true,
      },
    ],
    parameterFields: [
      {
        key: "project",
        label: "SLS 项目",
        type: "text",
        placeholder: "请输入 SLS 项目名称",
        required: false,
      },
      {
        key: "logstore",
        label: "Logstore",
        type: "text",
        placeholder: "请输入 Logstore 名称",
        required: false,
      },
    ],
    projectConfigFields: [
      {
        key: "queryPattern",
        label: "查询模板",
        type: "text",
        placeholder: "当前项目专属的日志查询模板",
        required: false,
      },
    ],
    logoIcon: "i-lucide-bar-chart-3",
    logoColor: "text-primary",
    comingSoon: false,
  },
  {
    id: "sentry",
    name: "Sentry",
    description: "错误追踪与性能监控",
    categoryId: "observability",
    connectionType: "oauth",
    connectionFields: [],
    parameterFields: [],
    projectConfigFields: [],
    logoIcon: "i-lucide-bug",
    logoColor: "text-error",
    comingSoon: true,
  },
];

export function generateMockConnections(): ToolConnection[] {
  return [];
}

export function generateMockToolConfigs(): ToolConfig[] {
  return [];
}

export function generateMockProjectToolConfigs(): ProjectToolConfig[] {
  return [];
}
